# Generated by Django 6.0.5 on 2026-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inletpoint',
            old_name='fid',
            new_name='pointid',
        ),
    ]
